name: test ASM

on: push

jobs:
  test-ASM:
    runs-on: ubuntu-latest
    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
    - name: make test && diff on .s
      run: |
        make test -C ./ASM/
